version: 2
registries:
  github-bitpesa:
    type: git
    url: https://github.com
    username: bolah2009
    password: ${{secrets.GITHUB_TOKEN}}

updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    registries: '*'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    reviewers:
      - 'bitpesa/engineering'
    commit-message:
      prefix: 'dependabot'
    open-pull-requests-limit: 3
    labels:
      - 'dependencies'
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: 'all'
    ignore:
      - dependency-name: '*'
        # Ignore all major version upgrades
        update-types: [version-update:semver-major, version-update:semver-minor]
    groups:
      # This is used to group updates instead of opening multiple PRs for version updates
      version-updates:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'patch'
      # This is used to group updates instead of opening multiple PRs for security updates
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'
        update-types:
          - 'patch'
