version: 2
registries:
  github-bitpesa:
    type: git
    url: https://github.com
    username: bolah2009
    password: ${{secrets.AZA_BACKSTAGE_CLASSIC}}

updates:
  - package-ecosystem: 'bundler'
    insecure-external-code-execution: allow
    directory: '/'
    registries: '*'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    reviewers:
      - 'bitpesa/engineering'
    commit-message:
      prefix: 'dependabot'
    open-pull-requests-limit: 3
    # ignore:
    #   - dependency-name: '*'
    #     # Ignore all major and minor version upgrades
    #     update-types: [version-update:semver-major, version-update:semver-minor]
    #   # gem 'dalli', '3.2.6' # A newer version is breaking the app with a TypeError
    #   - dependency-name: "dalli"
    groups:
      # This is used to group updates instead of opening multiple PRs for version updates
      patch-version-updates:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'patch'
      # This is used to group updates instead of opening multiple PRs for security updates
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'
        update-types:
          - 'patch'
      minor-version-updates:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - 'patch'
          - 'minor'
